import type { Report } from "./types";

// Branded, one-click PDF of the hiring debrief (Temi round-4 premium). Built programmatically
// with jsPDF (no HTML snapshot) so it renders cleanly regardless of app CSS.

type Meta = {
  role?: string;
  level?: string;
  interview_type?: string;
  difficulty?: string;
  persona?: string;
};

const REC_COLORS: Record<string, [number, number, number]> = {
  "strong hire": [16, 185, 129],
  hire: [34, 197, 94],
  "hire with reservations": [245, 158, 11],
  "no hire": [244, 63, 94],
};

const VIOLET: [number, number, number] = [124, 58, 237];
const INK: [number, number, number] = [40, 40, 60];

function label(key?: string): string {
  if (!key) return "";
  return key.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export async function downloadReportPdf(report: Report, meta: Meta = {}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  const contentW = W - M * 2;
  let y = 0;

  const setColor = (c: [number, number, number]) => doc.setTextColor(c[0], c[1], c[2]);

  function ensureSpace(need: number) {
    if (y + need > H - 60) {
      doc.addPage();
      y = 56;
    }
  }
  function paragraph(text: string, size = 11) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    setColor(INK);
    for (const ln of doc.splitTextToSize(text, contentW) as string[]) {
      ensureSpace(size + 6);
      doc.text(ln, M, y);
      y += size + 6;
    }
  }
  function heading(text: string) {
    y += 10;
    ensureSpace(26);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    setColor(VIOLET);
    doc.text(text, M, y);
    y += 18;
  }
  function bullets(items: string[]) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    for (const it of items) {
      const lines = doc.splitTextToSize(it, contentW - 16) as string[];
      ensureSpace(lines.length * 15 + 6);
      setColor(VIOLET);
      doc.text("•", M, y);
      setColor(INK);
      lines.forEach((ln) => {
        doc.text(ln, M + 14, y);
        y += 15;
      });
      y += 4;
    }
  }

  // --- header band ---
  doc.setFillColor(VIOLET[0], VIOLET[1], VIOLET[2]);
  doc.rect(0, 0, W, 92, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("DATAVERSE", M, 40);
  doc.setFontSize(21);
  doc.text("Interview Debrief", M, 66);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("AI Interview Coach", W - M, 40, { align: "right" });
  y = 122;

  // --- meta line ---
  setColor([110, 110, 130]);
  doc.setFontSize(10);
  const bits = [label(meta.persona), meta.role, meta.level, meta.interview_type, meta.difficulty].filter(Boolean);
  doc.text(bits.join("   ·   "), M, y);
  doc.text(new Date().toLocaleDateString(), W - M, y, { align: "right" });
  y += 22;

  // --- recommendation box ---
  const rec = report.recommendation || "";
  if (rec) {
    const c = REC_COLORS[rec.toLowerCase()] || VIOLET;
    doc.setFillColor(c[0], c[1], c[2]);
    doc.roundedRect(M, y, contentW, 48, 8, 8, "F");
    doc.setTextColor(255);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("HIRING RECOMMENDATION", M + 16, y + 19);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(rec, M + 16, y + 39);
    y += 68;
  }

  // --- body ---
  if (report.debrief_intro) paragraph(report.debrief_intro);
  if (report.did_well?.length) { heading("What you did well"); bullets(report.did_well); }
  if (report.held_back?.length) { heading("What held you back"); bullets(report.held_back); }
  if (report.how_to_improve?.length) { heading("How to improve"); bullets(report.how_to_improve); }
  if (report.absolute_hire) { heading("What would make you an absolute hire"); paragraph(report.absolute_hire); }

  // --- footer on every page ---
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setColor([150, 150, 160]);
    doc.text("Generated by Dataverse AI Interview Coach", M, H - 24);
    doc.text(`Page ${p} of ${pages}`, W - M, H - 24, { align: "right" });
  }

  doc.save("dataverse-interview-debrief.pdf");
}

// Focused one-page improvement roadmap (Temi round-4 premium).
export async function downloadRoadmapPdf(report: Report, meta: Meta = {}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 48;
  const contentW = W - M * 2;
  let y = 0;
  const setColor = (c: [number, number, number]) => doc.setTextColor(c[0], c[1], c[2]);

  doc.setFillColor(VIOLET[0], VIOLET[1], VIOLET[2]);
  doc.rect(0, 0, W, 92, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("DATAVERSE", M, 40);
  doc.setFontSize(21);
  doc.text("Your Improvement Roadmap", M, 66);
  y = 122;

  setColor([110, 110, 130]);
  doc.setFontSize(10);
  const bits = [label(meta.persona), meta.role, meta.interview_type, meta.difficulty].filter(Boolean);
  doc.text(bits.join("   ·   "), M, y);
  doc.text(new Date().toLocaleDateString(), W - M, y, { align: "right" });
  y += 26;

  function ensureSpace(n: number) { if (y + n > H - 60) { doc.addPage(); y = 56; } }
  function heading(t: string) {
    y += 10; ensureSpace(26);
    doc.setFont("helvetica", "bold"); doc.setFontSize(13); setColor(VIOLET);
    doc.text(t, M, y); y += 18;
  }
  function numbered(items: string[]) {
    doc.setFontSize(11);
    items.forEach((it, i) => {
      const lines = doc.splitTextToSize(it, contentW - 22) as string[];
      ensureSpace(lines.length * 15 + 8);
      doc.setFont("helvetica", "bold"); setColor(VIOLET); doc.text(`${i + 1}.`, M, y);
      doc.setFont("helvetica", "normal"); setColor(INK);
      lines.forEach((ln) => { doc.text(ln, M + 20, y); y += 15; });
      y += 5;
    });
  }
  function paragraph(t: string) {
    doc.setFont("helvetica", "normal"); doc.setFontSize(11); setColor(INK);
    for (const ln of doc.splitTextToSize(t, contentW) as string[]) { ensureSpace(17); doc.text(ln, M, y); y += 16; }
  }

  const steps = report.how_to_improve?.length ? report.how_to_improve : report.held_back || [];
  if (steps.length) { heading("Action steps"); numbered(steps); }
  if (report.weaknesses?.length) { heading("Focus areas"); paragraph(report.weaknesses.join(", ") + "."); }
  if (report.absolute_hire) { heading("Your target: an absolute hire"); paragraph(report.absolute_hire); }
  if (report.next_focus) { heading("Coach's note"); paragraph(report.next_focus); }

  doc.setFont("helvetica", "normal"); doc.setFontSize(8); setColor([150, 150, 160]);
  doc.text("Generated by Dataverse AI Interview Coach", M, H - 24);
  doc.save("dataverse-improvement-roadmap.pdf");
}
